### ISSUE TITLE
browserify form-data is not possible anymore

### ISSUE THREAD

**Issue by Ockejanssen** [form-data/form-data#139]
It is not possible to browserify form-data anymore. The version rc1 worked.

**Comment by alexindigo** [comment]
Thanks for the report. Is it erroring out? Care to provide the error?

**Comment by Ockejanssen** [comment]
./node_modules/.bin/browserify --ignore mime --ignore compress -t cssify -t jadeify -t brfs test/views/stats.js -o public/scripts/views/test/stats.js

.../node_modules/request/node_modules/form-data/lib/browser.js:1
(exports, require, module, __filename, __dirname) { module.exports = FormData;
                                                                     ^
ReferenceError: FormData is not defined
    at Object.<anonymous> (/.../node_modules/request/node_modules/form-data/lib/browser.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at nr (/.../node_modules/browserify/node_modules/module-deps/index.js:282:21)
    at /.../node_modules/browserify/node_modules/module-deps/index.js:273:21
    at onfile (/.../node_modules/browserify/node_modules/resolve/lib/async.js:51:21)

**Comment by alexindigo** [comment]
@DylanPiercey you have more experience with browserify and looks like it's related to your fix.

**Comment by DylanPiercey** [comment]
The current browser shim just exposes native formdata.@Ockejanssen Whats the purpose of using the browserified version of the node module?

To prevent this error we return a noop if the browser does not support formdata. (In the future we can provide a polyfill).

**Comment by Ockejanssen** [comment]
I just browserify the request module which uses form-data.

**Comment by DylanPiercey** [comment]
@Ockejanssen I don't know that using `request` with browserify is a practical use case. The file it generates is upward of 400kb (Just for ajax seems a bit absurd).

Currently we are working on turning this library into an isomorphic polyfill of sorts for the native form-data and as such the "browserified" version of this module simply returns the native module. I think that rather than encouraging browserifying modules not meant for the browser it would be best if `request` was modified to support the native form data module when run in the browser. I have no idea what opinions the owners of `request` have on isomorphic javascript but I could perhaps create a couple pr's to make this a reality.

If this is a real concern with a practical use case I would love to hear it and could be swayed to create a work-around.

If you are actually looking for an isomorphic solution I would check out ["isomorphic-fetch"](https://github.com/matthew-andrews/isomorphic-fetch) which works great with this module.

**Comment by simov** [comment]
@DylanPiercey our browserify tests are passing, although they are pretty basic. As for whether it's practical or not - if it was working up until now, and currently it's not, without a major release, then that's a bug that should be dealt with.

If you think that a small fix in request will do, I'm fine with it. I'm only concerned with adding ever more dependencies there. Request is also going to be refactored into more modular code base at some point, so once that happens handling such edge cases won't be a problem, because not everyone will install/load the multipart related logic in the first place.

**Comment by DylanPiercey** [comment]
@alexindigo I think we can remove this in favor of https://github.com/form-data/isomorphic-form-data.

**Comment by alexindigo** [comment]
@DylanPiercey I'd prefer to keep for those who doesn't want/can't do different packages in the browser/server and/or have third+ level dependency.

Although I'm yet fully understand logic behind Browserify's bundler. So if you and @simov think we'd be better of without it, I'm down.

**Comment by alexindigo** [comment]
Spring cleaning here. Seems like it's no longer an issue, or doesn't produce a lot of interest. I'll close it for now. Let me know if it's still a concern. Thanks.
