### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by obecny** [form-data/form-data#252]
I have an app build with electron and webpack, once the whole app is being packed when I try to start it I'm getting an error "window is undefined"
"The easy fix" is to simply remove browser param from package.json for "form-data" in node-modules.
Now the main question is that somehow related to form-data itself  or a webpack.
I'm using the electron-react-boilerplate from here:
https://github.com/chentsulin/electron-react-boilerplate/issues/385
I'm going to post the same question there too.
Any idea how this could be solved in a proper way would really useful,
thx :)

**Comment by alexindigo** [comment]
form-data is server side only, so it's not meant to go into the browser environment at all. There is browser specific file (with reference to native `FormData`) as workaround for browserify and webpack - quick&dirty solution. Although it's not the right solution. The right one would be to examine what and how you bundle and exclude the paths that leads to bundling form-data.

Are you bundling form-data directly or it's some dependency of your dependency?

Thank you.

**Comment by obecny** [comment]
It is dependancy of other dependancy. Once I want to "release" my electron app I need to basically create 2 js files with all needed dependancy. The mentioned electron boiler code example does that. I'm just guessing and might be wrong but when webpack is building the dependencies for all "requires" for some reason the react app (frontend) might request form-data as first then webpack saves form-data module as "module.exports = window.FormData;" and when next time the backend code requires form-data it returns the browser version instead of server version, and complains about window. 
Not sure yet but maybe it's a webpack issue with electron, that ignores the context (server / browser) in case the code requires the same library once in backend once in frontend whereas some of them might have "built-in" functionality then it fails ? 
The workaround you mentioned for browserify and webpack, did you mean that `adding` a `browser` param is wrong, or did you mean that `removing` (as I suggested) is wrong ?

**Comment by alexindigo** [comment]
I'm still trying to understand how bundler builds something and picks up code meant for the browser and winding up running it on the server.

Removing `browser` param would break it for other apps that are trying to build it for the browser and have packages like `superagent` that claims to work in the browser but has server-side only libraries in the dependency, so developers that use it have to come up with different workarounds.
I see it as a bug with that kind of packages either with the documentation or with dependencies.

Back to the issue, though.

Can you provide dependency tree of the project, so we can see where form-data gets pulled into browser path.

Thank you.

**Comment by worldjoe** [comment]
I can comment on this. I have the same problem. The problem is that webpack doesn't understand the electron-main target very well. In particular webpack will default to using the browser entry point unless  resolve:packageAlias is specified. The fix is to add this into obecny webpack file. OR to fix webpack to not default to browser when the target is electron or electron-main.

  resolve: {
    packageAlias: "main"
  },

https://github.com/chentsulin/electron-react-boilerplate/pull/410

**Comment by gzvirginhair** [comment]
All round, Indian hair extensions
![image](https://cloud.githubusercontent.com/assets/22812116/19472157/b06e7766-9558-11e6-8cc3-83a8f6461426.png) would be the most tough and might previous up to a full calendar year based upon how very well you're taking treatment of them. Artificial hair wigs typically lasts up to 6 months if you consistently wear them. Human hair could be flat ironed and synthetics are not able to.Hair wigs are a wonderful means to change your glance instantly and will contain extremely small fuss and if you might be undergoing chemotherapy. You will find many alternative hair wigs
![image](https://cloud.githubusercontent.com/assets/22812116/19472188/c5dc67de-9558-11e6-9a02-9013eb443209.png) available that are offered on the internet for yourself but still, the real hair ones stay to get the top mainly because they may be designed up of authentic and authentic hair.

**Comment by alexindigo** [comment]
Ouch, it's been 26 days already. Got carried away at work. I had changes for this one with more tests, will try to push it in tonight.

**Comment by TimothyGu** [comment]
@alexindigo, ping. Has there been any updates on this?

**Comment by alexindigo** [comment]
@TimothyGu seems like this solution fixes it https://github.com/form-data/form-data/issues/252#issuecomment-249051882 
And I added (#282) check for `self` and for `window` objects – it should cover most of the use cases, will publish 2.1.2 tonight.
