### ISSUE TITLE
Type 'FormData' is not assignable to type 'BodyInit'.

### ISSUE THREAD

**Issue by IRediTOTO** [form-data/form-data#512]
![image](https://user-images.githubusercontent.com/15695252/128391008-4ec88ecc-15b3-47dc-8739-795c59298d60.png)
```
Type 'FormData' is not assignable to type 'BodyInit'.
  Type 'FormData' is missing the following properties from type 'URLSearchParams': delete, get, getAll, has, and 7 more.
```

Hi, I get this error when use form-data with native fetch of NextJS, How can I fix this?

**Comment by tigerinus** [comment]
Hit the same issue when calling the native `fetch` as part of VSCode extension development. Any help?

**Comment by bfourgeaud** [comment]
I have the same error, no updates yet ?

**Comment by da1z** [comment]
2 years later no response?

**Comment by pedanmax** [comment]
please help me, i have the same problem.

**Comment by Mi-ch-ael** [comment]
Using `getBuffer` method of `FormData` should help:
```typescript
bodyInit = formData.getBuffer()
```

**Comment by kitayoshi** [comment]
@IRediTOTO 

Since I use NextJS too, I found its server-side runtime providing `FormData` (and `fetch`) polyfill.

So we could directely use `new FormData()` on the server-side code seamlessly.

- Refer: https://github.com/vercel/next.js/blob/27953213f8f0a8bce3ee17922256b3db40a2c639/packages/next/src/compiled/%40edge-runtime/primitives/fetch.js.LEGAL.txt#L4

For others:

- Node v18 add `FormData` API native support
- NextJS using `formdata-polyfill` https://github.com/jimmywarting/FormData too?
- Maybe using `formdata-node` https://github.com/octet-stream/form-data

**Comment by 76op** [comment]
```js
import { fetch, FormData } from 'undici'
```

Using undici.FormData works for me.

**Comment by teloryfrozy** [comment]
Hello,
My linter was complaining about a similar issue
`Argument type {method: string, body: FormData} is not assignable to parameter type RequestInit | undefined`

```ts
const formData = new FormData();
const response = await fetch(`${API_BASE_URL}user/article`, {
    method: "PUT",
    body: formData
});
```

Just replace `formData` by `formData.toString()` and you will be fine

**Comment by ljharb** [comment]
This package doesn’t contain types, so you’d need to address it somewhere else.
