### ISSUE TITLE
Content-Type not sent unless a filename is set

### ISSUE THREAD

**Issue by programble** [form-data/form-data#74]
See https://github.com/felixge/node-form-data/blob/master/lib/form_data.js#L127

Should be able to set a custom Content-Type without setting a filename.

**Comment by naugtur** [comment]
@alexindigo If filename field is required, the current version must throw an error if only contentType is set instead of silently failing (would save me 2h today)
As for the use cases for it - there's plenty of APIs that ignore filenames but accept a content type. I don't have a problem with sending spam as filename, but `form-data` needs to tell me I have to. And seeing as you didn't implement it to throw, I guess it's ok to send just the contentType anyway.

**Comment by NodeGuy** [comment]
:+1: for being able to set `Content-Type` to `application/json`.

**Comment by BernhardBln** [comment]
Alex - don't agree, when you send a json as one part, which should be processed by the server, you just want to set a name, but not a filename, as it will be parsed but not saved anywhere.

**Comment by DylanPiercey** [comment]
:-1: for "content-type" of "application/json". "multipart/form-data" should work just fine for this case? Also this would deviate from the spec.

**Comment by DylanPiercey** [comment]
Completely disregard my previous content, I was thinking the content-type header for the entire request.

This should be an easy fix. Will create a PR tomorrow.

**Comment by alexindigo** [comment]
Thanks to @DylanPiercey it's going out with `1.0.0-rc3`.

**Comment by alexindigo** [comment]
Fixed in #138
